import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const FONT_STYLESHEET_URL =
	"https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=Space+Grotesk:wght@500;700&display=swap";

const USER_AGENT =
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const srcDir = path.join(projectRoot, "src");
const fontsDir = path.join(srcDir, "assets", "fonts");
const localCssPath = path.join(srcDir, "fonts.local.css");

function extensionFromUrl(urlString) {
	const parsed = new URL(urlString);
	const ext = path.extname(parsed.pathname);
	return ext || ".woff2";
}

function fileNameForUrl(urlString) {
	const hash = createHash("sha1").update(urlString).digest("hex").slice(0, 16);
	return `google-font-${hash}${extensionFromUrl(urlString)}`;
}

async function fetchText(url) {
	const response = await fetch(url, {
		headers: {
			"User-Agent": USER_AGENT,
		},
	});

	if (!response.ok) {
		throw new Error(`Unable to fetch text from ${url} (HTTP ${response.status})`);
	}

	return response.text();
}

async function fetchBuffer(url) {
	const response = await fetch(url, {
		headers: {
			"User-Agent": USER_AGENT,
		},
	});

	if (!response.ok) {
		throw new Error(`Unable to fetch binary from ${url} (HTTP ${response.status})`);
	}

	const bytes = await response.arrayBuffer();
	return Buffer.from(bytes);
}

async function run() {
	await mkdir(fontsDir, { recursive: true });

	let css = await fetchText(FONT_STYLESHEET_URL);
	const matches = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/g)];
	const urls = [...new Set(matches.map((match) => match[1]))];

	for (const fontUrl of urls) {
		const fileName = fileNameForUrl(fontUrl);
		const localPath = path.join(fontsDir, fileName);
		const fontBuffer = await fetchBuffer(fontUrl);
		await writeFile(localPath, fontBuffer);
		css = css.replaceAll(fontUrl, `./assets/fonts/${fileName}`);
	}

	const outputCss = `/* Generated by scripts/download-fonts.mjs */\n${css}`;
	await writeFile(localCssPath, outputCss, "utf8");

	console.log(`Downloaded ${urls.length} font file(s) and wrote src/fonts.local.css`);
}

run().catch((error) => {
	console.error(error instanceof Error ? error.message : String(error));
	process.exitCode = 1;
});
